# Warning, this file is generated via "make manifests", don't edit it directly but instead change the files in config/manager
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/instance: system
    app.kubernetes.io/managed-by: kluctl
    app.kubernetes.io/name: namespace
    app.kubernetes.io/part-of: controller
    control-plane: controller-manager
  name: kluctl-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/instance: kluctl-controller
    app.kubernetes.io/managed-by: kluctl
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: controller
    control-plane: kluctl-controller
  name: kluctl-controller
  namespace: kluctl-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: kluctl-controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: kluctl-controller
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - kluctl
        - controller
        - run
        env: []
        image: ghcr.io/kluctl/kluctl:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: controller
        ports:
        - containerPort: 8080
          name: metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: kluctl-controller
      terminationGracePeriodSeconds: 10
