discriminator: kluctl.io-webui

args:
  - name: kluctl_image
    default: ghcr.io/kluctl/kluctl
  - name: kluctl_version
    default: v2.21.2
  - name: webui_args
    default: []
  - name: webui_envs
    default: []
  - name: webui_resources
    default: {}
  - name: webui_node_selectors
    default: {}
  - name: webui_tolerations
    default: []
  - name: webui_priority_class_name
    default: {}
