// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sourceoverride.proto

package sourceoverride

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Auth          *AuthMsg                 `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Response      *ResolveOverrideResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_sourceoverride_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourceoverride_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_sourceoverride_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyResponse) GetAuth() *AuthMsg {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ProxyResponse) GetResponse() *ResolveOverrideResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type ProxyRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Auth          *AuthMsg                `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Request       *ResolveOverrideRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_sourceoverride_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourceoverride_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_sourceoverride_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyRequest) GetAuth() *AuthMsg {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ProxyRequest) GetRequest() *ResolveOverrideRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type AuthMsg struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PubKey           []byte                 `protobuf:"bytes,1,opt,name=pubKey,proto3,oneof" json:"pubKey,omitempty"`
	Challenge        []byte                 `protobuf:"bytes,2,opt,name=challenge,proto3,oneof" json:"challenge,omitempty"`
	Pop              []byte                 `protobuf:"bytes,3,opt,name=pop,proto3,oneof" json:"pop,omitempty"`
	AuthError        *string                `protobuf:"bytes,4,opt,name=authError,proto3,oneof" json:"authError,omitempty"`
	PubKeyHash       *string                `protobuf:"bytes,5,opt,name=pubKeyHash,proto3,oneof" json:"pubKeyHash,omitempty"`
	ControllerSecret []byte                 `protobuf:"bytes,6,opt,name=controllerSecret,proto3,oneof" json:"controllerSecret,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthMsg) Reset() {
	*x = AuthMsg{}
	mi := &file_sourceoverride_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMsg) ProtoMessage() {}

func (x *AuthMsg) ProtoReflect() protoreflect.Message {
	mi := &file_sourceoverride_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMsg.ProtoReflect.Descriptor instead.
func (*AuthMsg) Descriptor() ([]byte, []int) {
	return file_sourceoverride_proto_rawDescGZIP(), []int{2}
}

func (x *AuthMsg) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *AuthMsg) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *AuthMsg) GetPop() []byte {
	if x != nil {
		return x.Pop
	}
	return nil
}

func (x *AuthMsg) GetAuthError() string {
	if x != nil && x.AuthError != nil {
		return *x.AuthError
	}
	return ""
}

func (x *AuthMsg) GetPubKeyHash() string {
	if x != nil && x.PubKeyHash != nil {
		return *x.PubKeyHash
	}
	return ""
}

func (x *AuthMsg) GetControllerSecret() []byte {
	if x != nil {
		return x.ControllerSecret
	}
	return nil
}

type ResolveOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoKey       string                 `protobuf:"bytes,1,opt,name=repoKey,proto3" json:"repoKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveOverrideRequest) Reset() {
	*x = ResolveOverrideRequest{}
	mi := &file_sourceoverride_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveOverrideRequest) ProtoMessage() {}

func (x *ResolveOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourceoverride_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveOverrideRequest.ProtoReflect.Descriptor instead.
func (*ResolveOverrideRequest) Descriptor() ([]byte, []int) {
	return file_sourceoverride_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveOverrideRequest) GetRepoKey() string {
	if x != nil {
		return x.RepoKey
	}
	return ""
}

type ResolveOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Artifact      []byte                 `protobuf:"bytes,2,opt,name=artifact,proto3,oneof" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveOverrideResponse) Reset() {
	*x = ResolveOverrideResponse{}
	mi := &file_sourceoverride_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveOverrideResponse) ProtoMessage() {}

func (x *ResolveOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourceoverride_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveOverrideResponse.ProtoReflect.Descriptor instead.
func (*ResolveOverrideResponse) Descriptor() ([]byte, []int) {
	return file_sourceoverride_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveOverrideResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ResolveOverrideResponse) GetArtifact() []byte {
	if x != nil {
		return x.Artifact
	}
	return nil
}

var File_sourceoverride_proto protoreflect.FileDescriptor

const file_sourceoverride_proto_rawDesc = "" +
	"\n" +
	"\x14sourceoverride.proto\x12\x0esourceoverride\"\x93\x01\n" +
	"\rProxyResponse\x12+\n" +
	"\x04auth\x18\x01 \x01(\v2\x17.sourceoverride.AuthMsgR\x04auth\x12H\n" +
	"\bresponse\x18\x02 \x01(\v2'.sourceoverride.ResolveOverrideResponseH\x00R\bresponse\x88\x01\x01B\v\n" +
	"\t_response\"\x8e\x01\n" +
	"\fProxyRequest\x12+\n" +
	"\x04auth\x18\x01 \x01(\v2\x17.sourceoverride.AuthMsgR\x04auth\x12E\n" +
	"\arequest\x18\x02 \x01(\v2&.sourceoverride.ResolveOverrideRequestH\x00R\arequest\x88\x01\x01B\n" +
	"\n" +
	"\b_request\"\xac\x02\n" +
	"\aAuthMsg\x12\x1b\n" +
	"\x06pubKey\x18\x01 \x01(\fH\x00R\x06pubKey\x88\x01\x01\x12!\n" +
	"\tchallenge\x18\x02 \x01(\fH\x01R\tchallenge\x88\x01\x01\x12\x15\n" +
	"\x03pop\x18\x03 \x01(\fH\x02R\x03pop\x88\x01\x01\x12!\n" +
	"\tauthError\x18\x04 \x01(\tH\x03R\tauthError\x88\x01\x01\x12#\n" +
	"\n" +
	"pubKeyHash\x18\x05 \x01(\tH\x04R\n" +
	"pubKeyHash\x88\x01\x01\x12/\n" +
	"\x10controllerSecret\x18\x06 \x01(\fH\x05R\x10controllerSecret\x88\x01\x01B\t\n" +
	"\a_pubKeyB\f\n" +
	"\n" +
	"_challengeB\x06\n" +
	"\x04_popB\f\n" +
	"\n" +
	"_authErrorB\r\n" +
	"\v_pubKeyHashB\x13\n" +
	"\x11_controllerSecret\"2\n" +
	"\x16ResolveOverrideRequest\x12\x18\n" +
	"\arepoKey\x18\x01 \x01(\tR\arepoKey\"l\n" +
	"\x17ResolveOverrideResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01\x12\x1f\n" +
	"\bartifact\x18\x02 \x01(\fH\x01R\bartifact\x88\x01\x01B\b\n" +
	"\x06_errorB\v\n" +
	"\t_artifact2\xb5\x01\n" +
	"\x05Proxy\x12P\n" +
	"\vProxyStream\x12\x1d.sourceoverride.ProxyResponse\x1a\x1c.sourceoverride.ProxyRequest\"\x00(\x010\x01\x12Z\n" +
	"\x0fResolveOverride\x12\x1c.sourceoverride.ProxyRequest\x1a'.sourceoverride.ResolveOverrideResponse\"\x00B0Z.github.com/kluctl/kluctl/v2/pkg/sourceoverrideb\x06proto3"

var (
	file_sourceoverride_proto_rawDescOnce sync.Once
	file_sourceoverride_proto_rawDescData []byte
)

func file_sourceoverride_proto_rawDescGZIP() []byte {
	file_sourceoverride_proto_rawDescOnce.Do(func() {
		file_sourceoverride_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sourceoverride_proto_rawDesc), len(file_sourceoverride_proto_rawDesc)))
	})
	return file_sourceoverride_proto_rawDescData
}

var file_sourceoverride_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sourceoverride_proto_goTypes = []any{
	(*ProxyResponse)(nil),           // 0: sourceoverride.ProxyResponse
	(*ProxyRequest)(nil),            // 1: sourceoverride.ProxyRequest
	(*AuthMsg)(nil),                 // 2: sourceoverride.AuthMsg
	(*ResolveOverrideRequest)(nil),  // 3: sourceoverride.ResolveOverrideRequest
	(*ResolveOverrideResponse)(nil), // 4: sourceoverride.ResolveOverrideResponse
}
var file_sourceoverride_proto_depIdxs = []int32{
	2, // 0: sourceoverride.ProxyResponse.auth:type_name -> sourceoverride.AuthMsg
	4, // 1: sourceoverride.ProxyResponse.response:type_name -> sourceoverride.ResolveOverrideResponse
	2, // 2: sourceoverride.ProxyRequest.auth:type_name -> sourceoverride.AuthMsg
	3, // 3: sourceoverride.ProxyRequest.request:type_name -> sourceoverride.ResolveOverrideRequest
	0, // 4: sourceoverride.Proxy.ProxyStream:input_type -> sourceoverride.ProxyResponse
	1, // 5: sourceoverride.Proxy.ResolveOverride:input_type -> sourceoverride.ProxyRequest
	1, // 6: sourceoverride.Proxy.ProxyStream:output_type -> sourceoverride.ProxyRequest
	4, // 7: sourceoverride.Proxy.ResolveOverride:output_type -> sourceoverride.ResolveOverrideResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sourceoverride_proto_init() }
func file_sourceoverride_proto_init() {
	if File_sourceoverride_proto != nil {
		return
	}
	file_sourceoverride_proto_msgTypes[0].OneofWrappers = []any{}
	file_sourceoverride_proto_msgTypes[1].OneofWrappers = []any{}
	file_sourceoverride_proto_msgTypes[2].OneofWrappers = []any{}
	file_sourceoverride_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sourceoverride_proto_rawDesc), len(file_sourceoverride_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sourceoverride_proto_goTypes,
		DependencyIndexes: file_sourceoverride_proto_depIdxs,
		MessageInfos:      file_sourceoverride_proto_msgTypes,
	}.Build()
	File_sourceoverride_proto = out.File
	file_sourceoverride_proto_goTypes = nil
	file_sourceoverride_proto_depIdxs = nil
}
