discriminator: kluctl.io-controller

args:
  - name: kluctl_image
    default: ghcr.io/kluctl/kluctl
  - name: kluctl_version
    default: v2.20.7
  - name: controller_args
    default: []
  - name: controller_envs
    default: []
  - name: controller_resources
    default: {}
