apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-helm-chart.fullname" . }}
  labels:
    {{- include "test-helm-chart.labels" . | nindent 4 }}
data:
  a: {{ .Values.data.a }}
  b: {{ .Values.data.b }}
  version: {{ .Chart.Version }}
  kubeVersion: {{ .Capabilities.KubeVersion }}
  {{ if .Values.lookup }}
  {{ $lookupObj := lookup "v1" "ConfigMap" .Values.lookupNamespace .Values.lookupName }}
  {{ if $lookupObj }}
  lookup: {{ $lookupObj.data.a -}}
  {{ else }}
  lookup: lookupReturnedNil
  {{ end }}
  {{ end }}
